openapi: "3.0.0"
info:
  version: 1.0.0
  title: Spotify Parametres
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /topsongs:
    get:
      summary: List top tracks
      operationId: listTopTracks
      tags:
        - topTracks
      parameters:
        - name: user_id
          in: query
          description: Type user and it's top 5 tracks
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersTop5"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    UsersTop5:
      type: object
      required:
        - user_id
        - nickname
        - top5
      properties:
        nickname:
          type: string
        top5:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string