openapi: 3.0.3
info:
  title: Parametres
  version: 1.0.0
  description: Parametres service
servers:
  - url: /api/v1
tags:
  - name: parametres
    description: Parametres
paths:
  /parametres/parametres:
    $ref: './parametres/paths.yaml#/Parametres'
  /parametres/parametres/{id}:
    $ref: './parametres/paths.yaml#/ParametresOne'
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'